/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * My API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customAxios } from '../../lib/axios';




export const getApiDocsJson = (

 signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api-docs.json`, method: 'GET', signal
    },
      );
    }




export const getGetApiDocsJsonQueryKey = () => {
    return [
    `/api-docs.json`
    ] as const;
    }


export const getGetApiDocsJsonQueryOptions = <TData = Awaited<ReturnType<typeof getApiDocsJson>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDocsJson>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiDocsJsonQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiDocsJson>>> = ({ signal }) => getApiDocsJson(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiDocsJson>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiDocsJsonQueryResult = NonNullable<Awaited<ReturnType<typeof getApiDocsJson>>>
export type GetApiDocsJsonQueryError = unknown


export function useGetApiDocsJson<TData = Awaited<ReturnType<typeof getApiDocsJson>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDocsJson>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDocsJson>>,
          TError,
          Awaited<ReturnType<typeof getApiDocsJson>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDocsJson<TData = Awaited<ReturnType<typeof getApiDocsJson>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDocsJson>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDocsJson>>,
          TError,
          Awaited<ReturnType<typeof getApiDocsJson>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDocsJson<TData = Awaited<ReturnType<typeof getApiDocsJson>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDocsJson>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiDocsJson<TData = Awaited<ReturnType<typeof getApiDocsJson>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDocsJson>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiDocsJsonQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






