/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * My API
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customAxios } from '../../lib/axios';




/**
 * @summary Get all products
 */
export const getApiProducts = (

 signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api/products/`, method: 'GET', signal
    },
      );
    }




export const getGetApiProductsQueryKey = () => {
    return [
    `/api/products/`
    ] as const;
    }


export const getGetApiProductsQueryOptions = <TData = Awaited<ReturnType<typeof getApiProducts>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiProductsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProducts>>> = ({ signal }) => getApiProducts(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProducts>>>
export type GetApiProductsQueryError = void


export function useGetApiProducts<TData = Awaited<ReturnType<typeof getApiProducts>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProducts>>,
          TError,
          Awaited<ReturnType<typeof getApiProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProducts<TData = Awaited<ReturnType<typeof getApiProducts>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProducts>>,
          TError,
          Awaited<ReturnType<typeof getApiProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProducts<TData = Awaited<ReturnType<typeof getApiProducts>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all products
 */

export function useGetApiProducts<TData = Awaited<ReturnType<typeof getApiProducts>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiProductsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Create product
 */
export const postApiProducts = (

 signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api/products/`, method: 'POST', signal
    },
      );
    }



export const getPostApiProductsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiProducts>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiProducts>>, TError,void, TContext> => {

const mutationKey = ['postApiProducts'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiProducts>>, void> = () => {


          return  postApiProducts()
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiProductsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiProducts>>>

    export type PostApiProductsMutationError = void

    /**
 * @summary Create product
 */
export const usePostApiProducts = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiProducts>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiProducts>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiProductsMutationOptions(options), queryClient);
    }
    /**
 * @summary Get product by slug
 */
export const getApiProductsSlugSlug = (
    slug: string,
 signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api/products/slug/${slug}`, method: 'GET', signal
    },
      );
    }




export const getGetApiProductsSlugSlugQueryKey = (slug: string,) => {
    return [
    `/api/products/slug/${slug}`
    ] as const;
    }


export const getGetApiProductsSlugSlugQueryOptions = <TData = Awaited<ReturnType<typeof getApiProductsSlugSlug>>, TError = void>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsSlugSlug>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiProductsSlugSlugQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProductsSlugSlug>>> = ({ signal }) => getApiProductsSlugSlug(slug, signal);





   return  { queryKey, queryFn, enabled: !!(slug), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProductsSlugSlug>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiProductsSlugSlugQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProductsSlugSlug>>>
export type GetApiProductsSlugSlugQueryError = void


export function useGetApiProductsSlugSlug<TData = Awaited<ReturnType<typeof getApiProductsSlugSlug>>, TError = void>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsSlugSlug>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsSlugSlug>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsSlugSlug>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductsSlugSlug<TData = Awaited<ReturnType<typeof getApiProductsSlugSlug>>, TError = void>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsSlugSlug>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsSlugSlug>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsSlugSlug>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductsSlugSlug<TData = Awaited<ReturnType<typeof getApiProductsSlugSlug>>, TError = void>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsSlugSlug>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get product by slug
 */

export function useGetApiProductsSlugSlug<TData = Awaited<ReturnType<typeof getApiProductsSlugSlug>>, TError = void>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsSlugSlug>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiProductsSlugSlugQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Get product by ID
 */
export const getApiProductsId = (
    id: string,
 signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api/products/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetApiProductsIdQueryKey = (id: string,) => {
    return [
    `/api/products/${id}`
    ] as const;
    }


export const getGetApiProductsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiProductsId>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiProductsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProductsId>>> = ({ signal }) => getApiProductsId(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProductsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiProductsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProductsId>>>
export type GetApiProductsIdQueryError = void


export function useGetApiProductsId<TData = Awaited<ReturnType<typeof getApiProductsId>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsId>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductsId<TData = Awaited<ReturnType<typeof getApiProductsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsId>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductsId<TData = Awaited<ReturnType<typeof getApiProductsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get product by ID
 */

export function useGetApiProductsId<TData = Awaited<ReturnType<typeof getApiProductsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiProductsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Update product
 */
export const putApiProductsId = (
    id: string,
 signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api/products/${id}`, method: 'PUT', signal
    },
      );
    }



export const getPutApiProductsIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiProductsId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiProductsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['putApiProductsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiProductsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  putApiProductsId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiProductsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiProductsId>>>

    export type PutApiProductsIdMutationError = void

    /**
 * @summary Update product
 */
export const usePutApiProductsId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiProductsId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiProductsId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPutApiProductsIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete product
 */
export const deleteApiProductsId = (
    id: string,
 signal?: AbortSignal
) => {


      return customAxios<void>(
      {url: `/api/products/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteApiProductsIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiProductsId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiProductsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiProductsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiProductsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiProductsId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiProductsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiProductsId>>>

    export type DeleteApiProductsIdMutationError = void

    /**
 * @summary Delete product
 */
export const useDeleteApiProductsId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiProductsId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiProductsId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiProductsIdMutationOptions(options), queryClient);
    }
